# -*- coding: utf-8 -*-
"""tarefa ebac

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-udwaKG_k0z22fZnFSVxNIpXjPcBEgd6
"""

num1 = input ('digite o primeiro número:') # recebe número de usúario
num2 = input ('digite o segundo numero:')

num1 = float(num1) # converte para float
num2 = float(num2)

print("\nEscolha a operação:") # mostra o menu de operações
print("1. subtração")
print("2. adição")
print("3. multiplicação")
print("4. divisão")

operação = input ("digite o numero da operação(1,2,3,4):") # lê a operação do usuário

if operação == '1':  # soma
    resultado = num1 + num2
    print(f"o resultado da adição é: {resultado}")
elif operação == '2': # subtração
    resultado = num1 - num2
    print(f"o resultado da subtração é: {resultado}")
elif operação == '3' : # multiplicação
    resultado = num1 * num2
    print(f"o resultado da multiplicação é: {resultado}")
elif operação == '4' : # divisão
    if num2 !=0: # evita divisão por zero
        resultado = num1 / num2
        print(f"o resultado da divisão é: {resultado}")
    else:
        print("erro:divisão por zero não permitida.")
else:
    print("operção invalida. Tente novamente.") # para entradas inválidas
